trigger: none
pr: none

stages:
- stage: Smallfiles
  jobs:
    - job: Build
      timeoutInMinutes: 360
      strategy:
        matrix:
          Ubuntu-22:
            imageName: "azcopyPerfUbuntu22"
            Description: "AzCopy Perf Test"

      pool:
        name: "AzCopyPerfTestUbuntu"
        demands:
          - ImageOverride -equals $(imageName)

      variables:
        - name: "AZCOPY_SHOW_PERF_STATES"
          value: "1"

      steps:
#        - checkout: none
#          path: "$(Agent.HomeDirectory)/go/src/github.com/Azure/azure-storage-azcopy/"

        - script: |
            echo $(Description)
            hostnamectl
          displayName: 'Print Agent Info'

        - task: GoTool@0
          inputs:
            version: '1.19.3'
        
        - script: |
            go build -o azcopy
            ./azcopy

      