trigger: none
pr: none

stages:
- stage: Smallfiles
  jobs:
    - job: Build
      timeoutInMinutes: 360
      strategy:
        matrix:
          Ubuntu-22:
            imageName: "azcopyPerfUbuntu22"
            Description: "AzCopy Perf Test"

      pool:
        name: "AzCopyPerfTestUbuntu"
        demands:
          - ImageOverride -equals $(imageName)

      variables:
        - group: NightlyBlobFuse
        - name: MOUNT_DIR
      
      steps:
        - checkout: none      
        
        - script: |
            echo $(Description)
            hostnamectl
          displayName: 'Print Agent Info'
      